@startuml
Agency -> Nats: publish
Nats -> Authentication: authenticate request
Nats <- Authentication: authentication response
Nats <-> Stan: stream
collections Processors
Processors <- Nats: subscribe
@enduml