{{- if (eq .Values.elasticsearch.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elasticsearch-external
  namespace: util
spec:
  hosts:
  - {{ .Values.fluentbit.backend.es.host }}
  ports:
  - number: {{ .Values.fluentbit.backend.es.port }}
    name: {{ .Values.fluentbit.backend.es.scheme }}
    protocol: {{ .Values.fluentbit.backend.es.scheme | upper }}
  location: MESH_EXTERNAL
---
{{- end }}
