apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: goodbye-natss-display
spec:
  broker: natss
  filter:
    attributes:
      source: sendoff
  subscriber:
    ref:
     apiVersion: v1
     kind: Service
     name: goodbye-display
