apiVersion: v1
kind: Pod
metadata:
  name: nats-box
  namespace: { { $.Release.Namespace | default "default" } }
  labels:
    app: nats-box
  annotations:
    sidecar.istio.io/inject: 'false'
spec:
  containers:
    - name: nats-box
      image: synadia/nats-box:0.1.0
      imagePullPolicy: Always
      env:
        - name: NATS_URL
          value: nats
        - name: STAN_CLUSTER
          value: nats-streaming
      command:
        - 'tail'
        - '-f'
        - '/dev/null'
