apiVersion: v1
kind: Pod
metadata:
  name: nats-box
  namespace: {{ $.Release.Namespace | default "default" }}
  labels:
    app: nats-box
  annotations:
    sidecar.istio.io/inject: 'false'
spec:
  {{- if false }}
  volumes:
    - name: creds-volume
      secret:
        secretName: stan-creds
  {{- end }}
  containers:
    - name: nats-box
      image: synadia/nats-box:0.1.0
      imagePullPolicy: Always
      resources:
        limits:
          cpu: {{ $.Values.resourcesLimitsCpu | default "500m" }}
          memory: {{ $.Values.resourcesLimitsMemory | default "512Mi" }}
        requests:
          cpu: {{ $.Values.resourcesRequestsCpu | default "50m" }}
          memory: {{ $.Values.resourcesRequestsMemory | default "128Mi" }}
      env:
        - name: NATS_URL
          value: nats-cluster-mgmt.{{ default "nats" $.Values.natsNamespace }}.svc.cluster.local:4222
        - name: STAN_CLUSTER
          value: nats-streaming
      command:
        - 'tail'
        - '-f'
        - '/dev/null'
      {{- if false }}
      volumeMounts:
        - name: creds-volume
          mountPath: /var/run/nats/secrets
      {{- end }}