apiVersion: v1
kind: ConfigMap
metadata:
  name: mds-config-files
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/organization-config/*.json").AsConfig | indent 2 }}
{{ (.Files.Glob "files/organization-config/*.json5").AsConfig | indent 2 }}
