{{- range $name, $cronjob := .Values.cronjobs }}
{{- if $cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $name }}-cron
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: {{ $cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          volumes:
          - name: mds-config-files
            configMap:
              name: mds-config-files
          containers:
          - name: {{ $name }}
            volumeMounts:
            - name: mds-config-files
              mountPath: /mds-config/
            image: {{ if $.Values.registry }}{{ printf "%s/" $.Values.registry }}{{- end}}{{ $name }}:{{ $cronjob.version }}
            {{- if $.Values.registry }}
            imagePullPolicy: IfNotPresent
            {{- end }}
            env:
            - name: TIMEZONE
              value: {{ $.Values.timezone }}
            - name: PG_USER
              value: {{ $.Values.postgresql.postgresqlUsername }}
            - name: PG_NAME
              value: {{ $.Values.postgresql.postgresqlDatabase }}
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: mds-secrets
                  key: postgresql-password
            - name: PG_HOST
            {{- if $.Values.postgresql.internal }}
              value: {{ $.Release.Namespace }}-postgresql.{{ $.Release.Namespace }}.svc.cluster.local
            {{- else }}
              value: {{ $.Values.postgresql.host }}
            {{- end }}
            {{- if $.Values.postgresql.hostReader }}
            - name: PG_HOST_READER
              value: {{ $.Values.postgresql.hostReader }}
            {{- end }}
            {{- if $.Values.postgresql.port }}
            - name: PG_PORT
              value: {{ $.Values.postgresql.port | quote }}
            {{- end}}
            {{- if $cronjob.migration }}
            - name: PG_MIGRATIONS
              value: {{ $cronjob.migration | quote }}
            {{- end }}
            - name: REDIS_HOST
            {{- if $.Values.redis.internal }}
              value: {{ $.Release.Namespace }}-redis-master.{{ $.Release.Namespace }}.svc.cluster.local
            {{- else }}
              value: {{ $.Values.redis.host }}
            {{- end }}
            - name: REDIS_PORT
              value: {{ $.Values.redis.port | quote }}
            - name: TENANT_ID
            {{- if hasKey $.Values "tenantId" }}
              value: {{ $.Values.tenantId }}
            {{- else }}
              value: {{ $.Release.Namespace }}
            {{- end }}
            {{- if $cronjob.env }}
{{ toYaml $cronjob.env | indent 12 }}
            {{- end }}
            {{- if hasKey $.Values "global" }}
            {{- if hasKey $.Values.global "env" }}
{{ toYaml $.Values.global.env | indent 12 }}
            {{- end }}
            {{- end }}
          restartPolicy: OnFailure
---
{{- end}}
{{- end}}
