{{- if (eq .Values.postgresql.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- if .Values.postgresql.hostReader }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-ro-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.hostReader }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- end }}
{{- if (eq .Values.redis.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.redis.host }}
  ports:
  - number: {{ .Values.redis.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- if hasKey .Values "egress" }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-other
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- range .Values.egress.hosts }}
  - {{ . }}
  {{- end }}
  ports:
  - number: 443
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
