{{- range $name, $api := .Values.apis }}
{{- if $api.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $name }}-route
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.domain | quote }}
  gateways:
  - mds-gateway
  http:
  - match:
    - uri:
        regex: {{ printf "^%s($|/.*$)" $api.pathPrefix | quote }}
    route:
    - destination:
        host: {{ $name }}.{{ $.Release.Namespace}}.svc.cluster.local
        port:
          number: 4000
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - PUT
      - DELETE
      allowCredentials: false
      allowHeaders:
      - Content-Type
      - Authorization
      maxAge: "10m"
---
{{- end }}
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mds-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  {{- if .Values.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
  {{- else }}
  - port:
      number: 80
      name: http
      protocol: HTTP
  {{- end }}
    hosts:
    - {{ .Values.domain | quote }}