{{- range $key, $processor := .Values.processors }}
{{- if $processor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }} # better name
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $key }}
  ports:
  - name: http-{{ $key }}
    port: 80
#    targetPort: 80
{{- end }}
{{- end }}
