{{- range $name, $deploy := .Values.deployments }}
{{- if $deploy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "mds.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $name }}
    {{- include "mds.selectorLabels" $ | nindent 4 }}
  ports:
  - name: http
    port: {{ $.Values.httpPort }}
  - name: repl
    port: {{ $.Values.replPort }}
{{- end }}
{{- end }}
