{{- range $name, $processor := .Values.processors }}
{{- if and $processor.enabled $processor.triggeredBy.trigger }}
{{- range $index, $trigger := $processor.triggeredBy.trigger }}
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ $name }}-{{ $trigger }}-trigger
  namespace: {{ $.Release.Namespace }}
spec:
  broker: natss
  filter:
    # sourceAndType:
    #   type: {{ $trigger }}
    attributes:
      type: {{ default "mds" $.Values.tenantId }}.{{ $trigger }}
    # fixme: unable to leverage other cloud-events field, eg: extensions
  subscriber:
   ref:
     apiVersion: v1
     kind: Service
     name: {{ $name }}
---
{{- end }}
{{- end }}
{{- end }}