{{- range $key, $processor := .Values.processors }}
{{- if and $processor.enabled $processor.triggeredBy.trigger }}
{{- range $index, $trigger := $processor.triggeredBy.trigger }}
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ $key }}-{{ $trigger }}-trigger
  namespace: {{ $.Release.Namespace }}
spec:
  broker: natss
  filter:
    # sourceAndType:
    #   type: {{ $trigger }}
    attributes:
      type: {{ $trigger }}
  subscriber:
   ref:
     apiVersion: v1
     kind: Service
     name: {{ $key }}
---
{{- end }}
{{- end }}
{{- end }}