apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats"
  namespace: {{ $.Release.Namespace | default "nats" }}
spec:
  size: {{ $.Values.clusterSize | default 3 }}
  version: 2.1.2
  pod:
    annotations:
      sidecar.istio.io/inject: "false"
  # operatorConfig:
  #   secret: operator-jwt
  #   systemAccount: "AASYS..."