apiVersion: v1
kind: Pod
metadata:
  name: dns
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    resources:
      limits:
        cpu: {{ $.Values.resourcesLimitsCpu | default "500m" }}
        memory: {{ $.Values.resourcesLimitsMemory | default "512Mi" }}
      requests:
        cpu: {{ $.Values.resourcesRequestsCpu | default "50m" }}
        memory: {{ $.Values.resourcesRequestsMemory | default "128Mi" }}
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
