prometheus:

  serverFiles:
    alerting_rules.yml:
      groups:

      - name: Nodes
        rules:

        - alert: NodeMemoryWarn
          expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low memory"
            description: "Low memory on node {{ $labels.kubernetes_node }} ({{ $value }}% available)"

        - alert: NodeMemoryCritical
          expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Very low memory"
            description: "Very low memory on node {{ $labels.kubernetes_node }} ({{ $value }}% available)"

        - alert: NodeDiskSpaceWarn
          expr: (node_filesystem_used_bytes / node_filesystem_size_bytes) * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low disk space"
            description: "Low disk space on node {{ $labels.kubernetes_node }} ({{ $value }}% available)"

        - alert: NodeDiskSpaceCritical
          expr: (node_filesystem_used_bytes / node_filesystem_size_bytes) * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Very low disk space"
            description: "Very low disk space on node {{ $labels.kubernetes_node }} ({{ $value }}% available)"

        - alert: NodeInodesWarn
          expr: node_filesystem_files_free{mountpoint ="/"} / node_filesystem_files{mountpoint ="/"} * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low filesystem inodes"
            description: "Low filesystem inodes on node {{ $labels.kubernetes_node }} ({{ $value }}% available)"

        - alert: NodeInodesCritical
          expr: node_filesystem_files_free{mountpoint ="/"} / node_filesystem_files{mountpoint ="/"} * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Low filesystem inodes"
            description: "Low filesystem inodes on node {{ $labels.kubernetes_node }} ({{ $value }}% available)"

        - alert: NodeCpuLoadWarn
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU load"
            description: "High CPU usage on node {{ $labels.kubernetes_node }} ({{ $value }}%)"

        - alert: NodeCpuLoadCritical
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU load"
            description: "High CPU usage on node {{ $labels.kubernetes_node }} ({{ $value }}%)"

      - name: Pods
        rules:

        - alert: PersistentVolumeDiskWarning
          expr: kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low PV disk space"
            description: "Low disk space for PV {{ $labels.namespace }}/{{ $labels.persistenvolumeclaim }} ({{ $value }}% available)"

        - alert: StatefulsetDown
          expr: (kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas_current) != 1
          for: 5m
          labels:
            severity: error
          annotations:
            summary: "StatefulSet down"
            description: "StatefulSet went down\n  VALUE = {{ $value }}"

        - alert: PodRestartsWarning
          expr: kube_pod_container_status_restarts_total > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod container frequent restarts"
            description: "Pod container {{ $labels.namespace }}/{{ $labels.pod }} restarted {{ $value }} times"

        - alert: PodContainerStatusWaiting
          expr: kube_pod_container_status_waiting_reason == 1
          for: 5m
          labels:
            severity: error
          annotations:
            summary: "Pod container waiting"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} waiting in state {{ $labels.reason }}"

  alertmanagerFiles:
    alertmanager.yml:

      global:
        slack_api_url: "https://hooks.slack.com/services/REDACTED/REDACTED/REDACTED"

      receivers:
      - name: default-receiver
        slack_configs:
        - channel: '#k8s-alerts'
          send_resolved: false
