prometheus:

  serverFiles:
    alerting_rules.yml:
      groups:

      - name: Nodes
        rules:

        - alert: NodeMemoryWarn
          expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low memory (instance {{ $labels.kubernetes_node }})"
            description: "Node memory is filling up (< 20% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeMemoryCritical
          expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Very low memory (instance {{ $labels.kubernetes_node }})"
            description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeDiskSpaceWarn
          expr: (node_filesystem_used_bytes / node_filesystem_size_bytes) * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low disk space (instance {{ $labels.kubernetes_node }})"
            description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeDiskSpaceCritical
          expr: (node_filesystem_used_bytes / node_filesystem_size_bytes) * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Very low disk space (instance {{ $labels.kubernetes_node }})"
            description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeInodesWarn
          expr: node_filesystem_files_free{mountpoint ="/"} / node_filesystem_files{mountpoint ="/"} * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Low inodes (instance {{ $labels.kubernetes_node }})"
            description: "Disk is almost running out of available inodes (< 20% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeInodesCritical
          expr: node_filesystem_files_free{mountpoint ="/"} / node_filesystem_files{mountpoint ="/"} * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Very Low inodes (instance {{ $labels.kubernetes_node }})"
            description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeCpuLoadWarn
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU load (instance {{ $labels.kubernetes_node }})"
            description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: NodeCpuLoadCritical
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU load (instance {{ $labels.kubernetes_node }})"
            description: "CPU load is > 90%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - name: Pods
        rules:

        - alert: PersistentVolumeOutOfDiskSpace
          expr: kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 < 20
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Volume out of disk space (instance {{ $labels.instance }})"
            description: "Volume is almost full (< 20% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: StatefulsetDown
          expr: (kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas_current) != 1
          for: 5m
          labels:
            severity: error
          annotations:
            summary: "StatefulSet down (instance {{ $labels.instance }})"
            description: "A StatefulSet went down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: PodRestartsWarning
          expr: kube_pod_container_status_restarts_total > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod frequent restarts (instance {{ $labels.instance }})"
            description: "Pod restarted {{ $value }} times in 5 minutes\n  LABELS: {{ $labels }}"

        - alert: PodContainerStatusWaiting
          expr: kube_pod_container_status_waiting_reason == 1
          for: 5m
          labels:
            severity: error
          annotations:
            summary: "Pod stuck in waiting state (instance {{ $labels.instance }})"
            description: "Pod stuck in state {{ $labels.reason }} for past 5 minutes\n  LABELS: {{ $labels }}"

alertmanagerFiles:
  alertmanager.yml:

    global:
      slack_api_url: "https://hooks.slack.com/services/REDACTED/REDACTED/REDACTED"

    receivers:
    - name: default-receiver
      slack_configs:
      - channel: '#k8s-alerts'
        send_resolved: false
