apiVersion: v2
appVersion: "2.1.4"
description: A Helm chart for the NATS.io High Speed Cloud Native Distributed Communications Technology.
name: nats
keywords:
  - nats
  - messaging
  - cncf
version: 0.2.0
home: http://github.com/nats-io/k8s
maintainers:
  - name: Waldemar Quevedo
    github: https://github.com/wallyqs
    email: wally@nats.io
icon: https://nats.io/img/logo.png
