import { Enum } from '@mds-core/mds-types'

const TABLE = Enum(
  'attachments',
  'audits',
  'audit_attachments',
  'audit_events',
  'devices',
  'events',
  'geographies',
  'geography_metadata',
  'policies',
  'policy_metadata',
  'telemetry'
)
export type TABLE_NAME = keyof typeof TABLE

const TABLES = Object.keys(TABLE) as TABLE_NAME[]
const DEPRECATED_TABLES = ['migrations', 'status_changes', 'stops', 'trips']

const COLUMN = Enum(
  'accuracy',
  'address',
  'altitude',
  'attachment_filename',
  'attachment_id',
  'audit_device_id',
  'audit_event_id',
  'audit_event_type',
  'audit_issue_code',
  'audit_subject_id',
  'audit_trip_id',
  'base_url',
  'capacity',
  'charge',
  'cross_street',
  'deleted',
  'description',
  'device_id',
  'effective_date',
  'end_time',
  'event_type',
  'event_type_reason',
  'geography_id',
  'geography_json',
  'geography_metadata',
  'heading',
  'id',
  'lat',
  'lng',
  'location_type',
  'mfgr',
  'migration',
  'mimetype',
  'model',
  'name',
  'note',
  'num_spots_available',
  'num_spots_disabled',
  'num_vehicles_available',
  'num_vehicles_disabled',
  'parking_verification_url',
  'platform_code',
  'policy_id',
  'policy_json',
  'policy_metadata',
  'post_code',
  'prev_geographies',
  'propulsion',
  'propulsion_type',
  'provider_device_id',
  'provider_id',
  'provider_name',
  'provider_vehicle_id',
  'publish_date',
  'recorded',
  'rental_methods',
  'reservation_cost',
  'service_area_id',
  'short_name',
  'speed',
  'stop_id',
  'stop_name',
  'telemetry_timestamp',
  'thumbnail_filename',
  'thumbnail_mimetype',
  'timestamp',
  'timezone',
  'trip_id',
  'type',
  'vehicle_id',
  'wheelchair_boarding',
  'year',
  'zone_id'
)
export type COLUMN_NAME = keyof typeof COLUMN
const COLUMNS = Object.keys(COLUMN) as COLUMN_NAME[]

const TABLE_COLUMNS: { [T in TABLE_NAME]: Readonly<COLUMN_NAME[]> } = {
  [TABLE.attachments]: [
    COLUMN.id,
    COLUMN.attachment_filename,
    COLUMN.attachment_id,
    COLUMN.base_url,
    COLUMN.mimetype,
    COLUMN.thumbnail_filename,
    COLUMN.thumbnail_mimetype,
    COLUMN.recorded
  ],
  [TABLE.audit_attachments]: [COLUMN.id, COLUMN.attachment_id, COLUMN.audit_trip_id, COLUMN.recorded],
  [TABLE.audits]: [
    COLUMN.id,
    COLUMN.audit_trip_id,
    COLUMN.audit_device_id,
    COLUMN.audit_subject_id,
    COLUMN.provider_id,
    COLUMN.provider_name,
    COLUMN.provider_vehicle_id,
    COLUMN.provider_device_id,
    COLUMN.timestamp,
    COLUMN.deleted,
    COLUMN.recorded
  ],
  [TABLE.audit_events]: [
    COLUMN.id,
    COLUMN.audit_trip_id,
    COLUMN.audit_event_id,
    COLUMN.audit_event_type,
    COLUMN.audit_issue_code,
    COLUMN.audit_subject_id,
    COLUMN.note,
    COLUMN.timestamp,
    COLUMN.lat,
    COLUMN.lng,
    COLUMN.speed,
    COLUMN.heading,
    COLUMN.accuracy,
    COLUMN.altitude,
    COLUMN.charge,
    COLUMN.recorded
  ],
  [TABLE.devices]: [
    COLUMN.id,
    COLUMN.device_id,
    COLUMN.provider_id,
    COLUMN.vehicle_id,
    COLUMN.type,
    COLUMN.propulsion,
    COLUMN.year,
    COLUMN.mfgr,
    COLUMN.model,
    COLUMN.recorded
  ],
  [TABLE.events]: [
    COLUMN.id,
    COLUMN.device_id,
    COLUMN.provider_id,
    COLUMN.timestamp,
    COLUMN.event_type,
    COLUMN.event_type_reason,
    COLUMN.telemetry_timestamp,
    COLUMN.trip_id,
    COLUMN.service_area_id,
    COLUMN.recorded
  ],
  [TABLE.geographies]: [
    COLUMN.id,
    COLUMN.description,
    COLUMN.effective_date,
    COLUMN.geography_id,
    COLUMN.geography_json,
    COLUMN.publish_date,
    COLUMN.prev_geographies,
    COLUMN.name
  ],
  [TABLE.geography_metadata]: [COLUMN.id, COLUMN.geography_id, COLUMN.geography_metadata],
  [TABLE.policies]: [COLUMN.id, COLUMN.policy_id, COLUMN.policy_json],
  [TABLE.policy_metadata]: [COLUMN.id, COLUMN.policy_id, COLUMN.policy_metadata],
  [TABLE.telemetry]: [
    COLUMN.id,
    COLUMN.device_id,
    COLUMN.provider_id,
    COLUMN.timestamp,
    COLUMN.lat,
    COLUMN.lng,
    COLUMN.speed,
    COLUMN.heading,
    COLUMN.accuracy,
    COLUMN.altitude,
    COLUMN.charge,
    COLUMN.recorded
  ]
}

export default {
  COLUMN,
  COLUMNS,
  DEPRECATED_TABLES,
  TABLE,
  TABLES,
  TABLE_COLUMNS
}
