{{- if .Values.natsbox.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-box
  labels:
    app: {{ .Release.Name }}-box
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  containers:
  - name: nats-box
    image: {{ .Values.natsbox.image }}
    imagePullPolicy: {{ .Values.natsbox.pullPolicy }}
    env:
    - name: NATS_URL
      value: {{ .Release.Name }}
    command:
     - "tail"
     - "-f"
     - "/dev/null"
{{- end }}
