import { VEHICLE_EVENT } from '@mds-core/mds-types'

const AVAILABLE_STATE_EDGES = {
  agency_drop_off: false,
  agency_pick_up: true,
  battery_charged: false,
  battery_low: true,
  comms_lost: true,
  comms_restored: false,
  compliance_pick_up: true,
  decommissioned: true,
  maintenance: true,
  maintenance_pick_up: true,
  missing: true,
  off_hours: true,
  on_hours: false,
  provider_drop_off: false,
  rebalance_pick_up: true,
  reservation_cancel: false,
  reservation_start: true,
  system_resume: false,
  system_suspend: true,
  trip_cancel: false,
  trip_end: false,
  trip_enter_jurisdiction: false,
  trip_leave_jurisdiction: false,
  trip_start: true,
  unspecified: true
}

const REMOVED_STATE_EDGES = {
  agency_drop_off: true,
  agency_pick_up: false,
  battery_charged: false,
  battery_low: false,
  comms_lost: false,
  comms_restored: false,
  compliance_pick_up: false,
  decommissioned: true,
  maintenance: false,
  maintenance_pick_up: false,
  missing: false,
  off_hours: false,
  on_hours: false,
  provider_drop_off: true,
  rebalance_pick_up: false,
  reservation_cancel: false,
  reservation_start: false,
  system_resume: false,
  system_suspend: false,
  trip_cancel: false,
  trip_end: false,
  trip_enter_jurisdiction: false,
  trip_leave_jurisdiction: false,
  trip_start: false,
  unspecified: true
}

const NON_OPERATIONAL_STATE_EDGES = {
  agency_drop_off: false,
  agency_pick_up: true,
  battery_charged: true,
  battery_low: false,
  comms_lost: true,
  comms_restored: false,
  compliance_pick_up: true,
  decommissioned: true,
  maintenance: true,
  maintenance_pick_up: true,
  missing: true,
  off_hours: false,
  on_hours: true,
  provider_drop_off: false,
  rebalance_pick_up: true,
  reservation_cancel: false,
  reservation_start: false,
  system_resume: true,
  system_suspend: false,
  trip_cancel: false,
  trip_end: false,
  trip_enter_jurisdiction: false,
  trip_leave_jurisdiction: false,
  trip_start: false,
  unspecified: true
}

const UNKNOWN_STATE_EDGES = {
  agency_drop_off: false,
  agency_pick_up: false,
  battery_charged: false,
  battery_low: false,
  comms_lost: false,
  comms_restored: false,
  compliance_pick_up: false,
  decommissioned: false,
  maintenance: false,
  maintenance_pick_up: false,
  missing: false,
  off_hours: false,
  on_hours: false,
  provider_drop_off: false,
  rebalance_pick_up: false,
  reservation_cancel: false,
  reservation_start: false,
  system_resume: false,
  system_suspend: false,
  trip_cancel: false,
  trip_end: false,
  trip_enter_jurisdiction: false,
  trip_leave_jurisdiction: false,
  trip_start: false,
  unspecified: false
}

const RESERVED_STATE_EDGES = {
  agency_drop_off: false,
  agency_pick_up: false,
  battery_charged: false,
  battery_low: false,
  comms_lost: true,
  comms_restored: false,
  compliance_pick_up: false,
  decommissioned: false,
  maintenance: false,
  maintenance_pick_up: false,
  missing: true,
  off_hours: false,
  on_hours: false,
  provider_drop_off: false,
  rebalance_pick_up: false,
  reservation_cancel: true,
  reservation_start: false,
  system_resume: false,
  system_suspend: false,
  trip_cancel: false,
  trip_end: false,
  trip_enter_jurisdiction: false,
  trip_leave_jurisdiction: false,
  trip_start: true,
  unspecified: true
}

const ON_TRIP_STATE_EDGES = {
  agency_drop_off: false,
  agency_pick_up: false,
  battery_charged: false,
  battery_low: false,
  comms_lost: true,
  comms_restored: false,
  compliance_pick_up: false,
  decommissioned: false,
  maintenance: false,
  maintenance_pick_up: false,
  missing: true,
  off_hours: false,
  on_hours: false,
  provider_drop_off: false,
  rebalance_pick_up: false,
  reservation_cancel: false,
  reservation_start: false,
  system_resume: false,
  system_suspend: false,
  trip_cancel: true,
  trip_end: true,
  trip_enter_jurisdiction: false,
  trip_leave_jurisdiction: true,
  trip_start: false,
  unspecified: false
}

const ELSEWHERE_STATE_EDGES = {
  agency_drop_off: true,
  agency_pick_up: true,
  battery_charged: false,
  battery_low: false,
  comms_lost: true,
  comms_restored: false,
  compliance_pick_up: true,
  decommissioned: true,
  maintenance: false,
  maintenance_pick_up: true,
  missing: true,
  off_hours: false,
  on_hours: false,
  provider_drop_off: true,
  rebalance_pick_up: true,
  reservation_cancel: false,
  reservation_start: false,
  system_resume: false,
  system_suspend: false,
  trip_cancel: false,
  trip_end: false,
  trip_enter_jurisdiction: true,
  trip_leave_jurisdiction: false,
  trip_start: false,
  unspecified: true
}

const UNSPECIFIED_STATE_EDGES = {
  ...AVAILABLE_STATE_EDGES,
  ...NON_OPERATIONAL_STATE_EDGES,
  ...REMOVED_STATE_EDGES,
  ...UNKNOWN_STATE_EDGES
}

export const expectedTransitions: {
  [A in VEHICLE_EVENT]: {
    [B in VEHICLE_EVENT]: boolean
  }
} = {
  /*
  agency_drop_off:,
  agency_pick_up:,
  battery_charged:,
  battery_low:,
  comms_lost:,
  comms_restored:,
  compliance_pick_up:,
  decommissioned:,
  maintenance:,
  maintenance_pick_up:,
  missing:,
  off_hours:,
  on_hours:,
  provider_drop_off:,
  rebalance_pick_up:,
  reservation_cancel:,
  reservation_start:,
  system_resume:,
  system_suspend:,
  trip_cancel:,
  trip_end:,
  trip_enter_jurisdiction:,
  trip_leave_jurisdiction:,
  trip_start:,
  unspecified:

    agency_drop_off: false,
    agency_pick_up: false,
    battery_charged: false,
    battery_low: false,
    comms_lost: false,
    comms_restored: false,
    compliance_pick_up: false,
    decommissioned: false,
    maintenance: false,
    maintenance_pick_up: false,
    missing: false,
    off_hours: false,
    on_hours: false,
    provider_drop_off: false,
    rebalance_pick_up: false,
    reservation_cancel: false,
    reservation_start: false,
    system_resume: false,
    system_suspend: false,
    trip_cancel: false,
    trip_end: false,
    trip_enter_jurisdiction: false,
    trip_leave_jurisdiction: false,
    trip_start: false,
    unspecified: false
  */
  agency_drop_off: AVAILABLE_STATE_EDGES,
  agency_pick_up: REMOVED_STATE_EDGES,
  battery_charged: AVAILABLE_STATE_EDGES,
  battery_low: NON_OPERATIONAL_STATE_EDGES,
  comms_lost: UNKNOWN_STATE_EDGES,
  comms_restored: {
    ...AVAILABLE_STATE_EDGES,
    ...ELSEWHERE_STATE_EDGES,
    ...RESERVED_STATE_EDGES,
    ...ON_TRIP_STATE_EDGES,
    ...NON_OPERATIONAL_STATE_EDGES
  },
  compliance_pick_up: REMOVED_STATE_EDGES,
  decommissioned: REMOVED_STATE_EDGES,
  maintenance: { ...AVAILABLE_STATE_EDGES, ...NON_OPERATIONAL_STATE_EDGES },
  maintenance_pick_up: REMOVED_STATE_EDGES,
  missing: UNKNOWN_STATE_EDGES,
  off_hours: NON_OPERATIONAL_STATE_EDGES,
  on_hours: AVAILABLE_STATE_EDGES,
  provider_drop_off: AVAILABLE_STATE_EDGES,
  rebalance_pick_up: REMOVED_STATE_EDGES,
  reservation_cancel: AVAILABLE_STATE_EDGES,
  reservation_start: RESERVED_STATE_EDGES,
  system_resume: AVAILABLE_STATE_EDGES,
  system_suspend: NON_OPERATIONAL_STATE_EDGES,
  trip_cancel: AVAILABLE_STATE_EDGES,
  trip_end: AVAILABLE_STATE_EDGES,
  trip_enter_jurisdiction: ON_TRIP_STATE_EDGES,
  trip_leave_jurisdiction: ELSEWHERE_STATE_EDGES,
  trip_start: ON_TRIP_STATE_EDGES,
  unspecified: UNSPECIFIED_STATE_EDGES
}
