# !! File must end with empty line !!
dependencies:
  - name: redis
    version: 10.5.7
    repository: alias:stable
    condition: redis.internal
  - name: postgresql
    repository: alias:stable
    version: 8.6.4
    condition: postgresql.internal
