apis:
  mds-provider:
    enabled: true
    pathPrefix: /provider
    version: latest
    migration: false
  mds-agency:
    enabled: true
    pathPrefix: /agency
    version: latest
    migration: false
  mds-audit:
    enabled: true
    pathPrefix: /audit
    version: latest
    migration: false
  mds-policy:
    enabled: true
    pathPrefix: /policy
    version: latest
    migration: false
  mds-compliance:
    enabled: true
    pathPrefix: /compliance
    version: latest
    migration: false
  mds-daily:
    enabled: true
    pathPrefix: /daily
    version: latest
    migration: false
  mds-metrics:
    enabled: true
    pathPrefix: /metrics
    version: latest
    migration: false
  mds-native:
    enabled: true
    pathPrefix: /native
    version: latest
    migration: false
  mds-policy-author:
    enabled: true
    pathPrefix: /policy-author
    version: latest
    migration: false
  mds-config:
    enabled: true
    pathPrefix: /config
    version: latest
    migration: false
processors:
  mds-event-processor:
    enabled: true
    version: latest
    migration: false
    triggeredBy:
      trigger: [event, telemetry]
  mds-trip-processor:
    enabled: true
    version: latest
    migration: false
    triggeredBy:
      cron: '* * * * *'
  mds-provider-processor:
    enabled: true
    version: latest
    migration: false
    triggeredBy:
      cron: '* * * * *'
  mds-web-sockets:
    enabled: true
    pathPrefix: /web-sockets
    version: latest
    migration: false
useEvents: true
tenantId:
timezone: America/Los_Angeles
registry:
useLatestImage: true
domain: '*'
tls:
  enabled: false
  domain:
jwt:
  issuer:
  enabled: false
  audiences: []
postgresql:
  internal: true
  host:
  hostReader:
  port: 5432
  existingSecret: mds-secrets
  password:
  postgresqlUsername: mdsadmin
  postgresqlDatabase: mds
  image:
    repository: postgres
    tag: 10
redis:
  internal: true
  host:
  port: 6379
  usePassword: false
  cluster:
    enabled: false
  master:
    disableCommands: []
  slave:
    disableCommands: []
slack:
  channel:
  token:
