apis:
  mds-agency:
    enabled: true
    pathPrefix: /agency
    version: latest
    migration: false
  mds-audit:
    enabled: true
    pathPrefix: /audit
    version: latest
    migration: false
  mds-policy:
    enabled: true
    pathPrefix: /policy
    version: latest
    migration: false
  mds-compliance:
    enabled: true
    pathPrefix: /compliance
    version: latest
    migration: false
  mds-daily:
    enabled: true
    pathPrefix: /daily
    version: latest
    migration: false
  mds-jurisdiction:
    enabled: true
    pathPrefix: /jurisdiction
    version: latest
    migration: false
  mds-jurisdiction-service:
    enabled: true
    version: latest
    migration: false
  mds-policy-author:
    enabled: true
    pathPrefix: /policy-author
    version: latest
    migration: false
  mds-geography:
    enabled: true
    pathPrefix: /geography
    version: latest
    migration: false
  mds-geography-author:
    enabled: true
    pathPrefix: /geography-author
    version: latest
    migration: false
  mds-geography-service:
    enabled: true
    version: latest
    migration: false
  mds-policy-service:
    enabled: true
    version: latest
    migration: false
  mds-ingest-service:
    enabled: true
    version: latest
    migration: false
  mds-attachment-service:
    enabled: true
    version: latest
    migration: false
  mds-audit-service:
    enabled: true
    version: latest
    migration: false
tenantId:
timezone: America/Los_Angeles
registry:
useLatestImage: true
domain: "*"
ingressgateway: ingressgateway
tls:
  enabled: false
  elbTermination: false
  domain:
jwt:
  issuer:
  enabled: false
  bypassInternal: false
  firstInstall: false
  audiences: []
nats:
  internal: true
  host:
  podAnnotations:
    sidecar.istio.io/inject: "false"
kafka:
  internal: true
  host:
  port: 9092
  podAnnotations:
    sidecar.istio.io/inject: "false"
postgresql:
  internal: true
  host:
  hostReader:
  port: 5432
  existingSecret: mds-secrets
  password: CHANGEME
  postgresqlUsername: mdsadmin
  postgresqlDatabase: mds
  image:
    repository: postgres
    tag: 10
redis:
  internal: true
  host:
  port: 6379
  usePassword: false
  cluster:
    enabled: false
  master:
    disableCommands: []
  slave:
    disableCommands: []
