apiVersion: "streaming.nats.io/v1alpha1"
kind: "NatsStreamingCluster"
metadata:
  name: "example-stan"
  namespace: default #{{ .Release.Namespace | default "default" }}
spec:
  size: 1 # 3
  natsSvc: "example-nats"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stan
  name: stan
  namespace: default #{{ .Release.Namespace | default "default" }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: nats-streaming
  type: ClusterIP
